modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/Wehavecookies56/Bonfires/master/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/bonfires" #optional
logoFile="bonfires.png" #optional
credits="FromSoftware and Bandai Namco for Dark Souls, Massive thanks to Prophecy_Wrecker for creating far better textures for everything in the mod" #optional
authors="${mod_authors}" #optional
description='''
${mod_description}
'''
[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    mandatory=true #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"